### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by hahwul** [hahwul/MobileHackersWeapons#3]
![mhw-og](https://user-images.githubusercontent.com/13212227/104400980-a49add00-5596-11eb-9b11-5246bc65c1ef.jpg)
![mhw](https://user-images.githubusercontent.com/13212227/104400983-a5cc0a00-5596-11eb-8aeb-81c747f26663.png)

**Comment by Lctsolutions** [comment]
Andrax ? Is there any reason you wouldnt include it that i should be aware of?
